version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - sudo yum update
      - curl -fsSL https://rpm.nodesource.com/setup_12.x | sudo bash -
      - sudo yum update
      - sudo yum install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build 
  post_build:
    commands:
      - mv appspec.yml ./dist/my-dream-app
      - mv scripts ./dist/my-dream-app
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/my-dream-app
